name: app_inv
description: "Proyecto de la Universidad"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cached_network_image: ^3.2.3
  get_server: ^1.2.1
  get: ^4.6.6
  shared_preferences: ^2.2.3
  d_view: ^0.0.2
  http: ^0.13.4
  d_method: ^0.0.2
  d_info: ^0.0.7
  d_input: ^0.0.2
  intl: ^0.17.0
  d_chart: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "assets/icon.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/